//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.03.01 at 01:01:35 AM EAT
//


package montran.message;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.acmt_022_001.IdentificationModificationAdviceV02;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.acmt_023_001.IdentificationVerificationRequestV02;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.acmt_024_001.IdentificationVerificationReportV02;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.camt_007_002.RequestToModifyPaymentV03;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.camt_029_001.ResolutionOfInvestigationV07;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.camt_056_001.FIToFIPaymentCancellationRequestV06;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.head_001_001.AppHdr;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pacs_002_001.FIToFIPaymentStatusReportV07;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pacs_004_001.PaymentReturnV07;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pacs_008_001.FIToFICustomerCreditTransferV07;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pacs_028_001.FIToFIPaymentStatusRequestV02;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pain_013_001.CreditorPaymentActivationRequestV07;
import ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pain_014_001.CreditorPaymentActivationRequestStatusReportV07;
/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AppHdr" type="{urn:iso:std:iso:20022:tech:xsd:head.001.001.01}BusinessApplicationHeaderV01"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ReqToModfyPmt" type="{urn:iso:std:iso:20022:tech:xsd:camt.007.002.03}RequestToModifyPaymentV03"/&gt;
 *           &lt;element name="RsltnOfInvstgtn" type="{urn:iso:std:iso:20022:tech:xsd:camt.029.001.07}ResolutionOfInvestigationV07"/&gt;
 *           &lt;element name="FIToFIPmtCxlReq" type="{urn:iso:std:iso:20022:tech:xsd:camt.056.001.06}FIToFIPaymentCancellationRequestV06"/&gt;
 *           &lt;element name="FIToFIPmtStsRpt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07}FIToFIPaymentStatusReportV07"/&gt;
 *           &lt;element name="PmtRtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.004.001.07}PaymentReturnV07"/&gt;
 *           &lt;element name="FIToFICstmrCdtTrf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.008.001.07}FIToFICustomerCreditTransferV07"/&gt;
 *           &lt;element name="FIToFIPmtStsReq" type="{urn:iso:std:iso:20022:tech:xsd:pacs.028.001.02}FIToFIPaymentStatusRequestV02"/&gt;
 *           &lt;element name="IdModAdvc" type="{urn:iso:std:iso:20022:tech:xsd:acmt.022.001.02}IdentificationModificationAdviceV02"/&gt;
 *           &lt;element name="IdVrfctnReq" type="{urn:iso:std:iso:20022:tech:xsd:acmt.023.001.02}IdentificationVerificationRequestV02"/&gt;
 *           &lt;element name="IdVrfctnRpt" type="{urn:iso:std:iso:20022:tech:xsd:acmt.024.001.02}IdentificationVerificationReportV02"/&gt;
 *           &lt;element name="CdtrPmtActvtnReq" type="{urn:iso:std:iso:20022:tech:xsd:pain.013.001.07}CreditorPaymentActivationRequestV07"/&gt;
 *           &lt;element name="CdtrPmtActvtnReqStsRpt" type="{urn:iso:std:iso:20022:tech:xsd:pain.014.001.07}CreditorPaymentActivationRequestStatusReportV07"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "appHdr",
        "idVrfctnRpt",
        "idVrfctnReq",
        "fiToFIPmtStsReq",
        "fiToFICstmrCdtTrf",
        "fiToFIPmtStsRpt",
})
@XmlRootElement(name = "Message")
public class Message implements Serializable {
    private final static long serialVersionUID = -1L;
    @XmlElement(name = "AppHdr", required = true)
    protected AppHdr appHdr;
    @XmlElement(name = "IdVrfctnRpt")
    protected IdentificationVerificationReportV02 idVrfctnRpt;
    @XmlElement(name = "IdVrfctnReq")
    protected IdentificationVerificationRequestV02 idVrfctnReq;

    @XmlElement(name = "FIToFIPmtStsReq")
    protected FIToFIPaymentStatusRequestV02 fiToFIPmtStsReq;
    @XmlElement(name = "FIToFICstmrCdtTrf")
    protected FIToFICustomerCreditTransferV07 fiToFICstmrCdtTrf;

    @XmlElement(name = "FIToFIPmtStsRpt")
    protected FIToFIPaymentStatusReportV07 fiToFIPmtStsRpt;


    /**
     * Gets the value of the appHdr property.
     *
     * @return
     *     possible object is
     *     {@link AppHdr }
     *
     */
    public AppHdr getAppHdr() {
        return appHdr;
    }

    /**
     * Sets the value of the appHdr property.
     *
     * @param value
     *     allowed object is
     *     {@link AppHdr }
     *
     */
    public void setAppHdr(AppHdr value) {
        this.appHdr = value;
    }

    /**
     * Gets the value of the idVrfctnRpt property.
     *
     * @return
     *     possible object is
     *     {@link IdentificationVerificationReportV02 }
     *
     */
    public IdentificationVerificationReportV02 getIdVrfctnRpt() {
        return idVrfctnRpt;
    }

    /**
     * Sets the value of the idVrfctnRpt property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentificationVerificationReportV02 }
     *
     */
    public void setIdVrfctnRpt(IdentificationVerificationReportV02 value) {
        this.idVrfctnRpt = value;
    }

    /**
     * Gets the value of the idVrfctnReq property.
     *
     * @return
     *     possible object is
     *     {@link IdentificationVerificationRequestV02 }
     *
     */
    public IdentificationVerificationRequestV02 getIdVrfctnReq() {
        return idVrfctnReq;
    }

    /**
     * Sets the value of the idVrfctnReq property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentificationVerificationRequestV02 }
     *
     */
    public void setIdVrfctnReq(IdentificationVerificationRequestV02 value) {
        this.idVrfctnReq = value;
    }

    /**
     * Gets the value of the fiToFIPmtStsReq property.
     *
     * @return
     *     possible object is
     *     {@link FIToFIPaymentStatusRequestV02 }
     *
     */
    public FIToFIPaymentStatusRequestV02 getFIToFIPmtStsReq() {
        return fiToFIPmtStsReq;
    }

    /**
     * Sets the value of the fiToFIPmtStsReq property.
     *
     * @param value
     *     allowed object is
     *     {@link FIToFIPaymentStatusRequestV02 }
     *
     */
    public void setFIToFIPmtStsReq(FIToFIPaymentStatusRequestV02 value) {
        this.fiToFIPmtStsReq = value;
    }

    /**
     * Gets the value of the fiToFICstmrCdtTrf property.
     *
     * @return
     *     possible object is
     *     {@link FIToFICustomerCreditTransferV07 }
     *
     */
    public FIToFICustomerCreditTransferV07 getFIToFICstmrCdtTrf() {
        return fiToFICstmrCdtTrf;
    }

    /**
     * Sets the value of the fiToFICstmrCdtTrf property.
     *
     * @param value
     *     allowed object is
     *     {@link FIToFICustomerCreditTransferV07 }
     *
     */
    public void setFIToFICstmrCdtTrf(FIToFICustomerCreditTransferV07 value) {
        this.fiToFICstmrCdtTrf = value;
    }

    /**
     * Gets the value of the fiToFIPmtStsRpt property.
     *
     * @return
     *     possible object is
     *     {@link FIToFIPaymentStatusReportV07 }
     *
     */
    public FIToFIPaymentStatusReportV07 getFIToFIPmtStsRpt() {
        return fiToFIPmtStsRpt;
    }

    /**
     * Sets the value of the fiToFIPmtStsRpt property.
     *
     * @param value
     *     allowed object is
     *     {@link FIToFIPaymentStatusReportV07 }
     *
     */
    public void setFIToFIPmtStsRpt(FIToFIPaymentStatusReportV07 value) {
        this.fiToFIPmtStsRpt = value;
    }
}
