//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//


package ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.camt_007_002;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.camt_007_002 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.camt_007_002
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestToModifyPaymentV03 }
     * 
     */
    public RequestToModifyPaymentV03 createRequestToModifyPaymentV03() {
        return new RequestToModifyPaymentV03();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AmountType3Choice }
     * 
     */
    public AmountType3Choice createAmountType3Choice() {
        return new AmountType3Choice();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification4 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification4 createBranchAndFinancialInstitutionIdentification4() {
        return new BranchAndFinancialInstitutionIdentification4();
    }

    /**
     * Create an instance of {@link BranchData2 }
     * 
     */
    public BranchData2 createBranchData2() {
        return new BranchData2();
    }

    /**
     * Create an instance of {@link Case2 }
     * 
     */
    public Case2 createCase2() {
        return new Case2();
    }

    /**
     * Create an instance of {@link CaseAssignment2 }
     * 
     */
    public CaseAssignment2 createCaseAssignment2() {
        return new CaseAssignment2();
    }

    /**
     * Create an instance of {@link CashAccount16 }
     * 
     */
    public CashAccount16 createCashAccount16() {
        return new CashAccount16();
    }

    /**
     * Create an instance of {@link CashAccountType2 }
     * 
     */
    public CashAccountType2 createCashAccountType2() {
        return new CashAccountType2();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     * 
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link EquivalentAmount2 }
     * 
     */
    public EquivalentAmount2 createEquivalentAmount2() {
        return new EquivalentAmount2();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification7 }
     * 
     */
    public FinancialInstitutionIdentification7 createFinancialInstitutionIdentification7() {
        return new FinancialInstitutionIdentification7();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link InstructionForCreditorAgent1 }
     * 
     */
    public InstructionForCreditorAgent1 createInstructionForCreditorAgent1() {
        return new InstructionForCreditorAgent1();
    }

    /**
     * Create an instance of {@link InstructionForNextAgent1 }
     * 
     */
    public InstructionForNextAgent1 createInstructionForNextAgent1() {
        return new InstructionForNextAgent1();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation3 }
     * 
     */
    public OriginalGroupInformation3 createOriginalGroupInformation3() {
        return new OriginalGroupInformation3();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link Party7Choice }
     * 
     */
    public Party7Choice createParty7Choice() {
        return new Party7Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification32 }
     * 
     */
    public PartyIdentification32 createPartyIdentification32() {
        return new PartyIdentification32();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation22 }
     * 
     */
    public PaymentTypeInformation22 createPaymentTypeInformation22() {
        return new PaymentTypeInformation22();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     * 
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     * 
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     * 
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link RemittanceAmount1 }
     * 
     */
    public RemittanceAmount1 createRemittanceAmount1() {
        return new RemittanceAmount1();
    }

    /**
     * Create an instance of {@link RemittanceInformation5 }
     * 
     */
    public RemittanceInformation5 createRemittanceInformation5() {
        return new RemittanceInformation5();
    }

    /**
     * Create an instance of {@link RequestedModification2 }
     * 
     */
    public RequestedModification2 createRequestedModification2() {
        return new RequestedModification2();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link SettlementInformation15 }
     * 
     */
    public SettlementInformation15 createSettlementInformation15() {
        return new SettlementInformation15();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link UnderlyingGroupInformation1 }
     * 
     */
    public UnderlyingGroupInformation1 createUnderlyingGroupInformation1() {
        return new UnderlyingGroupInformation1();
    }

    /**
     * Create an instance of {@link UnderlyingPaymentInstruction1 }
     * 
     */
    public UnderlyingPaymentInstruction1 createUnderlyingPaymentInstruction1() {
        return new UnderlyingPaymentInstruction1();
    }

    /**
     * Create an instance of {@link UnderlyingPaymentTransaction1 }
     * 
     */
    public UnderlyingPaymentTransaction1 createUnderlyingPaymentTransaction1() {
        return new UnderlyingPaymentTransaction1();
    }

    /**
     * Create an instance of {@link UnderlyingStatementEntry1 }
     * 
     */
    public UnderlyingStatementEntry1 createUnderlyingStatementEntry1() {
        return new UnderlyingStatementEntry1();
    }

    /**
     * Create an instance of {@link UnderlyingTransaction1Choice }
     * 
     */
    public UnderlyingTransaction1Choice createUnderlyingTransaction1Choice() {
        return new UnderlyingTransaction1Choice();
    }

}
