//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//


package ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.camt_007_002;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.io.Serializable;


/**
 * <p>Java class for UnderlyingTransaction1Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnderlyingTransaction1Choice"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Initn" type="{urn:iso:std:iso:20022:tech:xsd:camt.007.002.03}UnderlyingPaymentInstruction1"/&gt;
 *           &lt;element name="IntrBk" type="{urn:iso:std:iso:20022:tech:xsd:camt.007.002.03}UnderlyingPaymentTransaction1"/&gt;
 *           &lt;element name="StmtNtry" type="{urn:iso:std:iso:20022:tech:xsd:camt.007.002.03}UnderlyingStatementEntry1"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnderlyingTransaction1Choice", propOrder = {
    "stmtNtry",
    "intrBk",
    "initn"
})
public class UnderlyingTransaction1Choice
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "StmtNtry")
    protected UnderlyingStatementEntry1 stmtNtry;
    @XmlElement(name = "IntrBk")
    protected UnderlyingPaymentTransaction1 intrBk;
    @XmlElement(name = "Initn")
    protected UnderlyingPaymentInstruction1 initn;

    /**
     * Gets the value of the stmtNtry property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlyingStatementEntry1 }
     *     
     */
    public UnderlyingStatementEntry1 getStmtNtry() {
        return stmtNtry;
    }

    /**
     * Sets the value of the stmtNtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlyingStatementEntry1 }
     *     
     */
    public void setStmtNtry(UnderlyingStatementEntry1 value) {
        this.stmtNtry = value;
    }

    /**
     * Gets the value of the intrBk property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlyingPaymentTransaction1 }
     *     
     */
    public UnderlyingPaymentTransaction1 getIntrBk() {
        return intrBk;
    }

    /**
     * Sets the value of the intrBk property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlyingPaymentTransaction1 }
     *     
     */
    public void setIntrBk(UnderlyingPaymentTransaction1 value) {
        this.intrBk = value;
    }

    /**
     * Gets the value of the initn property.
     * 
     * @return
     *     possible object is
     *     {@link UnderlyingPaymentInstruction1 }
     *     
     */
    public UnderlyingPaymentInstruction1 getInitn() {
        return initn;
    }

    /**
     * Sets the value of the initn property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnderlyingPaymentInstruction1 }
     *     
     */
    public void setInitn(UnderlyingPaymentInstruction1 value) {
        this.initn = value;
    }

}
