//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//


package ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.camt_029_001;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentCancellationRejection2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PaymentCancellationRejection2Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="LEGL"/&gt;
 *     &lt;enumeration value="AGNT"/&gt;
 *     &lt;enumeration value="CUST"/&gt;
 *     &lt;enumeration value="ARDT"/&gt;
 *     &lt;enumeration value="NOAS"/&gt;
 *     &lt;enumeration value="NOOR"/&gt;
 *     &lt;enumeration value="AC04"/&gt;
 *     &lt;enumeration value="AM04"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PaymentCancellationRejection2Code")
@XmlEnum
public enum PaymentCancellationRejection2Code {

    LEGL("LEGL"),
    AGNT("AGNT"),
    CUST("CUST"),
    ARDT("ARDT"),
    NOAS("NOAS"),
    NOOR("NOOR"),
    @XmlEnumValue("AC04")
    AC_04("AC04"),
    @XmlEnumValue("AM04")
    AM_04("AM04");
    private final String value;

    PaymentCancellationRejection2Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentCancellationRejection2Code fromValue(String v) {
        for (PaymentCancellationRejection2Code c: PaymentCancellationRejection2Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
