//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.004.001.07", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ke.co.pesalink.papss.incoming.credittransferproducerservice.dictionary.pacs_004_001;
