//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//


package montran.rcon;

import jakarta.xml.bind.annotation.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="settlement" type="{urn:montran:rcon.001}SettlementInfo"/&gt;
 *         &lt;element name="tran" type="{urn:montran:rcon.001}Transaction" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="totalSent" type="{urn:montran:rcon.001}Summary"/&gt;
 *         &lt;element name="totalReceived" type="{urn:montran:rcon.001}Summary"/&gt;
 *         &lt;element name="total" type="{urn:montran:rcon.001}Summary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settlement",
    "tren",
    "totalSent",
    "totalReceived",
    "total"
})
@XmlRootElement(name = "recon")
public class Recon
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected SettlementInfo settlement;
    @XmlElement(name = "tran")
    protected List<Transaction> tren;
    @XmlElement(required = true)
    protected Summary totalSent;
    @XmlElement(required = true)
    protected Summary totalReceived;
    @XmlElement(required = true)
    protected Summary total;

    /**
     * Gets the value of the settlement property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementInfo }
     *     
     */
    public SettlementInfo getSettlement() {
        return settlement;
    }

    /**
     * Sets the value of the settlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementInfo }
     *     
     */
    public void setSettlement(SettlementInfo value) {
        this.settlement = value;
    }

    /**
     * Gets the value of the tren property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the tren property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transaction }
     * 
     * 
     */
    public List<Transaction> getTren() {
        if (tren == null) {
            tren = new ArrayList<Transaction>();
        }
        return this.tren;
    }

    /**
     * Gets the value of the totalSent property.
     * 
     * @return
     *     possible object is
     *     {@link Summary }
     *     
     */
    public Summary getTotalSent() {
        return totalSent;
    }

    /**
     * Sets the value of the totalSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary }
     *     
     */
    public void setTotalSent(Summary value) {
        this.totalSent = value;
    }

    /**
     * Gets the value of the totalReceived property.
     * 
     * @return
     *     possible object is
     *     {@link Summary }
     *     
     */
    public Summary getTotalReceived() {
        return totalReceived;
    }

    /**
     * Sets the value of the totalReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary }
     *     
     */
    public void setTotalReceived(Summary value) {
        this.totalReceived = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Summary }
     *     
     */
    public Summary getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary }
     *     
     */
    public void setTotal(Summary value) {
        this.total = value;
    }

}
