//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//


package montran.rcon;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;


/**
 * <p>Java class for Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transaction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ref" type="{urn:montran:rcon.001}Max35Text" /&gt;
 *       &lt;attribute name="processTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="amount" type="{urn:montran:rcon.001}Amount_SimpleType" /&gt;
 *       &lt;attribute name="tranSeq" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="dbtrAgtId" type="{urn:montran:rcon.001}ClrSysMmbId" /&gt;
 *       &lt;attribute name="cdtrAgtId" type="{urn:montran:rcon.001}ClrSysMmbId" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transaction")
public class Transaction
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "ref")
    protected String ref;
    @XmlAttribute(name = "processTime")
    @XmlSchemaType(name = "dateTime")
    protected Calendar processTime;
    @XmlAttribute(name = "amount")
    protected BigDecimal amount;
    @XmlAttribute(name = "tranSeq")
    protected Long tranSeq;
    @XmlAttribute(name = "dbtrAgtId")
    protected String dbtrAgtId;
    @XmlAttribute(name = "cdtrAgtId")
    protected String cdtrAgtId;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the processTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getProcessTime() {
        return processTime;
    }

    /**
     * Sets the value of the processTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessTime(Calendar value) {
        this.processTime = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the tranSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTranSeq() {
        return tranSeq;
    }

    /**
     * Sets the value of the tranSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTranSeq(Long value) {
        this.tranSeq = value;
    }

    /**
     * Gets the value of the dbtrAgtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrAgtId() {
        return dbtrAgtId;
    }

    /**
     * Sets the value of the dbtrAgtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrAgtId(String value) {
        this.dbtrAgtId = value;
    }

    /**
     * Gets the value of the cdtrAgtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrAgtId() {
        return cdtrAgtId;
    }

    /**
     * Sets the value of the cdtrAgtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrAgtId(String value) {
        this.cdtrAgtId = value;
    }

}
