//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.01 at 01:01:35 AM EAT 
//


package montran.positions;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;


/**
 * <p>Java class for SnapshotInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnapshotInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="conditions" type="{urn:montran:positions.001}ConditionsList" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="instgAgtCrlSysId" use="required" type="{urn:montran:positions.001}ClrSysMmbId" /&gt;
 *       &lt;attribute name="lastTranSeq" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnapshotInfo", propOrder = {
    "conditions"
})
public class SnapshotInfo
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected List<ConditionsList> conditions;
    @XmlAttribute(name = "instgAgtCrlSysId", required = true)
    protected String instgAgtCrlSysId;
    @XmlAttribute(name = "lastTranSeq", required = true)
    protected long lastTranSeq;
    @XmlAttribute(name = "timestamp", required = true)
//    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar timestamp;

    /**
     * Gets the value of the conditions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the conditions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionsList }
     * 
     * 
     */
    public List<ConditionsList> getConditions() {
        if (conditions == null) {
            conditions = new ArrayList<ConditionsList>();
        }
        return this.conditions;
    }

    /**
     * Gets the value of the instgAgtCrlSysId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstgAgtCrlSysId() {
        return instgAgtCrlSysId;
    }

    /**
     * Sets the value of the instgAgtCrlSysId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstgAgtCrlSysId(String value) {
        this.instgAgtCrlSysId = value;
    }

    /**
     * Gets the value of the lastTranSeq property.
     * 
     */
    public long getLastTranSeq() {
        return lastTranSeq;
    }

    /**
     * Sets the value of the lastTranSeq property.
     * 
     */
    public void setLastTranSeq(long value) {
        this.lastTranSeq = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(Calendar value) {
        this.timestamp = value;
    }

}
